- platform: darksky
  api_key: !secret ds_api
  monitored_conditions:
    - summary
    - icon
    - temperature
    - precip_type
    - precip_intensity
    - precip_probability
    - apparent_temperature
    - wind_bearing
    - wind_speed
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - minutely_summary
    - hourly_summary
    - daily_summary
    - uv_index
